# Generated by Django 5.2.8 on 2025-12-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
