# Generated by Django 5.2.8 on 2025-12-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='site',
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica'), ('AD', 'Administrador')], default='PF', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
