# Generated by Django 5.2.8 on 2025-12-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pessoafisica_site_profile_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoafisica',
            old_name='nome',
            new_name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='email',
        ),
    ]
