# Generated by Django 5.2.8 on 2025-12-10 01:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_nome_pessoafisica_nome_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[accounts.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='rg',
            field=models.CharField(max_length=20, validators=[accounts.models.validar_rg]),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[accounts.models.validar_cnpj]),
        ),
    ]
